# Generated by Django 5.2.6 on 2025-09-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='successstories',
            options={'verbose_name_plural': 'Success Stories'},
        ),
    ]
